### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by Anasme** [zhaoterryy/mkdocs-pdf-export-plugin#58]
Hello I'm tryin to build my docs and export some pdf with your plugin but got this error : 

```
 docs master ✗ mkdocs serve    
INFO    -  Building documentation... 
/usr/local/lib/python3.5/dist-packages/weasyprint/document.py:35: UserWarning: There are known rendering problems and missing features with cairo < 1.15.4. WeasyPrint may work with older versions, but please read the note about the needed cairo version on the "Install" page of the documentation before 
reporting bugs. http://weasyprint.readthedocs.io/en/latest/install.html
  'There are known rendering problems and missing features with '
INFO    -  Cleaning site directory 
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/censored/.local/lib/python3.5/site-packages/mkdocs/__main__.py", line 194, in <module>
    cli()
  File "/home/censored/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/censored/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/censored/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/censored/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/censored/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/censored/.local/lib/python3.5/site-packages/mkdocs/__main__.py", line 127, in serve_command
    livereload=livereload
  File "/home/censored/.local/lib/python3.5/site-packages/mkdocs/commands/serve.py", line 117, in serve
    config = builder()
  File "/home/censored/.local/lib/python3.5/site-packages/mkdocs/commands/serve.py", line 112, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/home/censored/.local/lib/python3.5/site-packages/mkdocs/commands/build.py", line 282, in build
    build_pages(config, dirty=dirty)
  File "/home/censored/.local/lib/python3.5/site-packages/mkdocs/commands/build.py", line 216, in build_pages
    site_navigation = config['plugins'].run_event('nav', site_navigation, config=config)
  File "/home/censored/.local/lib/python3.5/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
TypeError: on_nav() missing 1 required positional argument: 'files'
```

- configuration:
```
docs master ✗ sudo pip3 show mkdocs
Name: mkdocs
Version: 1.0.4
Summary: Project documentation with Markdown.
Home-page: https://www.mkdocs.org
Author: Tom Christie
Author-email: tom@tomchristie.com
License: BSD
Location: /usr/local/lib/python3.5/dist-packages
Requires: tornado, PyYAML, Markdown, livereload, click, Jinja2
```
```
λ  docs master ✗ sudo pip3 --version
sudo pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.5)
λ  docs master ✗ sudo python --version
Python 3.5.3
```
```
λ  docs master ✗ sudo pip3 --version
sudo pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.5)
λ  docs master ✗ sudo python --version
Python 3.5.3
```

I tried to follow the readme, and recommandations... it's only workin on my gitlab CI on alpine, but I need to launch it on my debian WSL image to dev.

Thanks  you in advance for your help

**Comment by jrazgunas** [comment]
I'm seeing the same issue, was there ever a resolution to this?
