### ISSUE TITLE
Can't Export to PDF

### ISSUE THREAD

**Issue by DuckHunter213** [zhaoterryy/mkdocs-pdf-export-plugin#68]
Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Scripts\mkdocs.exe\__main__.py", line 9, in <module>
  File "c:\python\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\python\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python\lib\site-packages\mkdocs\__main__.py", line 163, in build_command
    ), dirty=not clean)
  File "c:\python\lib\site-packages\mkdocs\commands\build.py", line 240, in build
    config = config['plugins'].run_event('config', config)
  File "c:\python\lib\site-packages\mkdocs\plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "c:\python\lib\site-packages\mkdocs_pdf_export_plugin\plugin.py", line 43, in on_config
    from .renderer import Renderer
  File "c:\python\lib\site-packages\mkdocs_pdf_export_plugin\renderer.py", line 6, in <module>
    from weasyprint import HTML, Document
  File "c:\python\lib\site-packages\weasyprint\__init__.py", line 440, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "c:\python\lib\site-packages\weasyprint\css\__init__.py", line 30, in <module>
    from . import computed_values, media_queries
  File "c:\python\lib\site-packages\weasyprint\css\computed_values.py", line 17, in <module>
    from .. import text
  File "c:\python\lib\site-packages\weasyprint\text.py", line 14, in <module>
    import cairocffi as cairo
  File "c:\python\lib\site-packages\cairocffi\__init__.py", line 50, in <module>
    ('libcairo.so', 'libcairo.2.dylib', 'libcairo-2.dll'))
  File "c:\python\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e

**Comment by DuckHunter213** [comment]
Install GTK+

**Comment by DuckHunter213** [comment]
Install GTK+

**Comment by DuckHunter213** [comment]
Install GTK+

**Comment by DuckHunter213** [comment]
Install GTK+
